CREATE TABLE films(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);
CREATE TABLE category(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT,id_parent INTEGER);
CREATE TABLE category_images(id INTEGER PRIMARY KEY AUTOINCREMENT, value BLOB);
